call HW_SERVER_HOST.sh.bat

if exist c:\Xilinx\SDK\2017.2\bin\xsct.bat set XSCT=call c:\Xilinx\SDK\2017.2\bin\xsct.bat -quiet -interactive
if exist c:\Xilinx\SDK\2017.3\bin\xsct.bat set XSCT=call c:\Xilinx\SDK\2017.3\bin\xsct.bat -quiet -interactive

call HW_SERVER_HOST.sh.bat
%XSCT% -eval "source init.tcl; puts \"running mrd 0xfec00000\"; set var [mrd -value 0xfec00000]; puts \"dec : $var\"; source vartohex.tcl; "
