echo %HOST%
echo %TARGETDIR%
set NEWDIR=%TARGETDIR:~20%
echo %NEWDIR%
echo \\%HOST%%NEWDIR%
rem start c:\totalcmd\TOTALCMD.EXE /O %TARGETDIR% \\%HOST%%NEWDIR%

set "variable=\\%HOST%%NEWDIR%
set "variable=%variable:/=\%"
start C:\"Program Files"\"Double Commander"\doublecmd.exe -C --no-console --no-splash %TARGETDIR% "%variable%"
rem bring to front
c:\UniServer\www\doc\files\ThisPC\nircmd\nircmdc.exe win activate title "Double Commander 0.8.4 beta build 8272M; 2018/08/18"
