cd %cd%

set UNIQFNAME=%date%
:: remove '.'
set UNIQFNAME=%UNIQFNAME:/=%
:: remove ':'
set UNIQFNAME=%UNIQFNAME%-%time%
set UNIQFNAME=%UNIQFNAME:.=%
set UNIQFNAME=%UNIQFNAME::=%
set UNIQFNAME=%UNIQFNAME: =%

echo %UNIQFNAME%.odt


copy c:\UniServer\www\common\open_command_files\blank.odt %cd%\%UNIQFNAME%.odt /Y
start c:\"Program Files (x86)"\"Microsoft Office"\Office12\WINWORD.EXE %cd%\%UNIQFNAME%.odt /q
exit


