echo default route
ping -n 1 172.19.31.254
echo ------------------------
echo dns 1
ping -n 1 172.19.31.254
echo ------------------------
echo dns 2
ping -n 1 172.19.31.254
echo ------------------------
echo ping laptop-7kqrmtc0 with the ip and resolve name
ping -n 1 192.168.1.100
echo ------------------------
echo ping laptop-7kqrmtc0 and resolve name
ping -n 1 -a laptop-7kqrmtc0
echo ------------------------
pause
