set THISDIR=%CD%
set REPONAME=WIN10LAP
cd c:\UniServer\www\doc\files\
echo "# REPONAME" >> README.md
echo "# Repository of code from the DELL Windows 10 laptop" >> README.md
git init
git add README.md
git commit -m "Creation of the root"

curl -u mlerman:compagniePI https://api.github.com/user/repos -d "{\"name\" : \"%REPONAME%\"}"

git remote add origin https://github.com/mlerman/%REPONAME%.git
git push -u origin master

rem returning to the directory
cd %THISDIR%
pause