set THISDIR=%CD%
set REPONAME=WIN10LAP
cd c:\UniServer\www\doc\files\
rem echo "# REPONAME" >> README.md
rem echo "# Repository of code from the DELL Windows 10 laptop" >> README.md
git init
rem git add README.md
rem git commit -m "Creation of the root"

rem curl -u mlerman:compagniePI https://api.github.com/user/repos -d "{\"name\" : \"%REPONAME%\"}"

git remote add origin https://github.com/mlerman/%REPONAME%.git
rem git push -u origin master

rem returning to the directory
cd %THISDIR%
pause