cls
@echo off
set COUNTER=0
:loop
set /A COUNTER+=1
rem echo %COUNTER%
if not exist scr%COUNTER%.png ( echo filename is available
copy c:\UniServer\www\doc\files\common\open_command_files\blank.png  scr%COUNTER%.png
start %windir%\system32\mspaint.exe scr%COUNTER%.png
copy .head temp
echo ^<img src=^"scr%COUNTER%.png^"/^> > .head
echo ^<hr/^> >> .head
type temp>>.head
del temp /Q
goto suite
)
goto loop

:suite

