echo focus on the vivado window
c:/UniServer/www/doc/files/ThisPC/nircmd/nircmdc.exe win settopmost class "SWT_Window0" 1
c:/UniServer/www/doc/files/ThisPC/nircmd/nircmdc.exe win settopmost class "SWT_Window0" 0

if exist c:\Xilinx\SDK\2017.2\bin\xsct.bat set XSCT=call c:\Xilinx\SDK\2017.2\bin\xsct.bat -quiet -interactive
if exist c:\Xilinx\SDK\2017.3\bin\xsct.bat set XSCT=call c:\Xilinx\SDK\2017.3\bin\xsct.bat -quiet -interactive

call HW_SERVER_HOST.sh.bat
type reset_processor.txt |  %XSCT%

