@echo off
cls
if exist putty.log del putty.log /Q
call get_zedboard_IP.bat
rem Zedboard
rem start c:\UniServer\www\doc\files\ThisPC\putty\putty.exe -ssh root@%ZEDIP% -pw root
rem Localhost
rem start c:\UniServer\www\doc\files\ThisPC\putty\putty.exe -ssh mlerman@%ZEDIP% -pw normerel
call c:\UniServer\www\local\set_xlnxp.bat

start c:\UniServer\www\doc\files\ThisPC\putty\putty.exe -ssh mikhaell@%ZEDIP% -pw "%XLNXP%"
exit
